defaults: &defaults
  additional_info: true
  contact_phone: true
  description: true
  electricity: true
  light: true
  fire: true
  noise: true
  nature: false
  moop: false
  plan: false
  cocreation: true
  neighbors: true
  recycling: false
  budgetplan: true
  seeking_members: true
  granting: false
  # Only people with "Ticket records of phone and email can register"
  user_authentication_codes: false
  user_authentication_vs_tixwise: true
  add_to_list: true
  granting_active: false
  footer_text: true
  footer_logo: false
  creation_sidebar_welcome: true
  safetybag: false
  person_early_arrival:  <%= ENV['PERSON_EARLY_ARRIVAL'] or false %>
  person_has_ticket:  <%= ENV['PERSON_HAS_TICKET'] or false %>
  multi_lang_support: <%= ENV['MULTI_LANG_SUPPORT'] or false %>
  disable_open_new_dream: <%= ENV['disable_open_new_dream'] or false %>
  disable_edit_safetybag: <%= ENV['disable_edit_safetybag'] or false %>
  disable_edit_budget: <%= ENV['disable_edit_budget'] or false %>
  google_drive_integration: <%= ENV['GOOGLE_DRIVE_INTEGRATION'] or false %>
  show_point_of_contact: <%= ENV['SHOW_POINT_OF_CONTACT'] or false %>
  show_safety_file_comments: <%= ENV['SHOW_SAFETY_FILE_COMMENTS'] or false %>
  recaptcha: <%= ENV['RECAPTCHA'] or false %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
